spring.datasource.url=jdbc:mysql://trolley.proxy.rlwy.net:44624/railway?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=MBSgLfTXEQPTisnGWDjenAXBCOlwfmrA

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true